---
- hosts: ubuntuos
  become: yes
  tasks: 
  - name: i want to install webserver on ubuntu 
    apt:
      name: apache2 
      state: present
    notify: startwebserver

  - name: i want to copy index file into all nodes
    template: 
      src: myindex.j2
      dest: /var/www/html/index.html
    notify: startwebserver

  handlers:
  - name: startwebserver 
    service:
      name: apache2 
      state: restarted        

