---
- hosts: ubuntuos
  become: yes
  tasks:
  - name: i want to install webserver on ubuntu
    apt:
      name: apache2
      state: present

  - name: start the service
    service:
      name: apache2
      state: started

  - name: i want to copy index file into node
    template:
      src: myindex.j2
      dest: /var/www/html/index.html

  - name: restart the service
    service:
      name: apache2
      state: restarted